# Generated by Django 4.2.24 on 2025-10-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myGroceryApp', '0002_alter_mycustomuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='productStockModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_qty', models.CharField(max_length=50)),
                ('item_price', models.CharField(max_length=50)),
                ('item_category', models.CharField(max_length=50)),
            ],
        ),
    ]
